### ISSUE TITLE
Plugin configuration for the whole site not working

### ISSUE THREAD

**Issue by daza1** [docpad/docpad-plugin-sitemap#12]
Changed the docpad.coffee file to configure for the whole site but no changes made.
Works for each document when specify in metadata, but not with plugin config in docpad.coffee.
Any suggestions?
eg
```yaml

    plugins:
      sitemap:
        cachetime: 600000
        changefreq: 'monthly'
        priority: 1.0
        filePath: 'sitemap.xml'
```
